In [1]:
#Python Libraries

In [2]:
#Python libraries = python libraries are the collection of functions and methods that allows you to perform many actions
#without writing your code

In [3]:
#Numpy,pandas,matplotlib

In [4]:
#Numpy

In [5]:
#Numpy = numpy stands for numerical python is the core library for numeric and scientific computing

In [6]:
#It consists of multi-dimensional array objects and a collection of routines for processing those arrays

In [7]:
import numpy as np

In [8]:
l1 = [1,2,3,4,5]

In [10]:
n1 = np.array(l1)

In [11]:
n1

array([1, 2, 3, 4, 5])

In [12]:
type(n1)

numpy.ndarray

In [14]:
n2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
type(n2)

numpy.ndarray

In [17]:
#Initializing the array with zeros

In [20]:
n3 = np.zeros((2,3)) #rows,column

In [21]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
type(n3)

numpy.ndarray

In [23]:
n4 = np.zeros((10,10))

In [24]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
type(n4)

numpy.ndarray

In [26]:
#Initializing the numpy array with same number then use full method

In [31]:
n5 = np.full((3,3), 55) #dimension,number

In [32]:
n5

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [33]:
type(n5)

numpy.ndarray

In [34]:
#Initializing numpy array within in a range we use arange method

In [37]:
n6 = np.arange(50,101)

In [38]:
n6

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [39]:
type(n6)

numpy.ndarray

In [43]:
n7 = np.arange(50,500,10) #50 is starting,500 is end,10 is skip/jump

In [44]:
n7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

In [45]:
type(n7)

numpy.ndarray

In [46]:
#Initializing numpy array with random numbers using random module inside that randint method

In [49]:
import numpy as np
n9 = np.random.randint(100,200,10) #100 is starting,200 is ending,10 is number of random number
n9

array([199, 193, 106, 174, 142, 101, 120, 133, 195, 114])

In [50]:
type(n9)

numpy.ndarray

In [51]:
#Checking the shape of the numpy array

In [52]:
n1 = np.array([[1,2,3,4], [5,6,7,8] ])

In [53]:
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
n1.shape

(2, 4)

In [55]:
n1.shape = (4,2)

In [56]:
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
n1.shape = (8,1)

In [61]:
n1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [62]:
#Joining numpy arrays

In [63]:
#Three methods are there
#vstack()
#hstack()
#column_stack()

In [64]:
n1 = np.array([1,2,3])

In [65]:
n2 = np.array([4,5,6])

In [67]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [69]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
#Numpy intersection and difference

In [71]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [76]:
np.intersect1d(n1,n2) #intersect1d is a function used for finding intersection

array([50, 60])

In [77]:
np.setdiff1d(n1,n2) #setdiff1d is a function used for finding set difference

array([10, 20, 30, 40])

In [78]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [79]:
#Numpy array mathematics

In [80]:
#Addition of numpy arrays

In [81]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [82]:
#Sum of all elements in the array

In [83]:
np.sum([n1,n2])

100

In [84]:
#If you want to just add the column value

In [85]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [86]:
#If you want to just add the row value

In [87]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [88]:
#Numpy array mathematics

In [89]:
n1 = np.array([10,20,30])

In [90]:
#Scalar addition for each value of array

In [91]:
n1 + 5

array([15, 25, 35])

In [92]:
#Scalar subtract for each value of array

In [93]:
n1 - 5

array([ 5, 15, 25])

In [94]:
#Scalar multiplication for each value of array

In [95]:
n1 * 10

array([100, 200, 300])

In [96]:
#Scalar division for each value of array

In [97]:
n1/5

array([2., 4., 6.])

In [98]:
#Numpy math functions

In [99]:
n1 = np.random.randint(1,50,10)

In [100]:
n1

array([18, 22, 39,  2, 29, 43, 21, 13, 12, 18])

In [101]:
#Mean

In [102]:
np.mean(n1)

21.7

In [103]:
#Median

In [104]:
np.median(n1)

19.5

In [105]:
 #Standard deviation

In [106]:
np.std(n1)

11.798728745080972

In [107]:
#Numpy save and load

In [108]:
n1

array([18, 22, 39,  2, 29, 43, 21, 13, 12, 18])

In [109]:
np.save('my_array',n1)

In [110]:
new_n1 = np.load('my_array.npy')

In [111]:
new_n1

array([18, 22, 39,  2, 29, 43, 21, 13, 12, 18])